# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ethics of Self-Driving Cars - Safety and Liability
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

postcss:
  cache: false

# Exclude from processing
exclude:
  - .bundle
  - .jekyll-cache/
  - .sass-cache/
  - "*.code-workspace"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - "gemfiles/"
  - "/licenses/"
  - "LICENSE.md"
  - "README.md"
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Always include in processing
keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
