# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ethics of Self-Driving Cars - Safety and Liability
description: >- # this means to ignore newlines until "baseurl:"
  COMP501 Assignment 3
baseurl: "" # the subpath of your site, e.g. /blog
url: "a30812.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "https://a30812.github.io"
logo: "/assets/0812_wide.svg"
color_scheme: "light"

# Build settings
markdown: kramdown
destination: docs
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-link-attributes
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - .bundle
  - .jekyll-cache/
  - .sass-cache/
  - "*.code-workspace"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - "gemfiles/"
  - "/licenses/"
  - "LICENSE.md"
  - "README.md"
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Always include in processing
keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

external_links:
  enabled: true
  rel: external
  target: _top

aux_links:
  GitHub Repository: https://github.com/a30812/a30812.github.io/
